### PR TITLE
FIX: featureFlags.set() does not update cached featureFlags #42

### PR DESCRIPTION
**Pull request by dejewi**

### CODE REVIEW

**Comment by mjt01** [comment]
Thanks for putting this together, are you able to provide a test that fails to capture your fix?

**Comment by dejewi** [comment]
Hi Michael, Did you had chance to review my last update?

**Comment by mjt01** [comment]
Looks good to me, thanks for making those changes.

**Comment by mjt01** [comment]
@dejewi I have reverted this PR in v1.6.0 based on https://github.com/mjt01/angular-feature-flags/issues/44. Having reviewed the issues raised I agree that the correct behaviour is not what was set last, rather that the local override wins. Sorry for the confusion, I'm not actively working on this module so it can be hard to build enough context to review intent thoroughly enough.

**Comment by dejewi** [comment]
ohh :(
How about if I will introduce additional parameter to control overriding eg. by default `featureFlags.set()` will not override feature flags stored in localstorage but if we will set/or pass additional boolean parameter set on `true` then we will override feature flags?

**Comment by mjt01** [comment]
On reflection I actually think you are using the model incorrectly (hence the roll back). The `enable` function is about setting a local override for what is otherwise the source of truth. The idea of setting a local override then overriding the override using `set` does not sound right.

You're probably after a `resetAll` that deletes all overrides right?

**Comment by dejewi** [comment]
Generally I don't use `resetAll`. My use case is very simple:

1. in config phase set default feature flags required to run application (or just in case if feature flag service is not available), eg flag `ARE_FEATURE_FLAGS_LOADED`
```js
myApp.config(function(featureFlagsProvider) {
  featureFlagsProvider.setInitialFlags([
    { "key": "ARE_FEATURE_FLAGS_LOADED", "active": false, "name": "...", "description": "..." },
  ]);
});
```

2. in run phase set whole the most up-to-date feature flag list (with eg. `ARE_FEATURE_FLAGS_LOADED` feature flag set on `true`)
```js
myApp.run(function(featureFlags, $http) {
  featureFlags.set($http.get('/api/flags'));
});
```


And after this two steps `ARE_FEATURE_FLAGS_LOADED` is set on `false` instead of `true`

**Pull request merged**
